# Generated by Django 5.0.3 on 2024-03-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
